### ISSUE TITLE
Fix regex find to not explode on empty-length hits

### ISSUE THREAD

**Issue by dbkaplun** [slap-editor/slap#108]

**Comment by NiXXeD** [comment]
I was trying to reproduce this while I was looking at another issue, but am not sure what "explode" means here. Assuming you mean error, but I don't get an error. It just says no matches, as expected.
<img width="1440" alt="screen shot 2015-12-15 at 2 13 45 pm" src="https://cloud.githubusercontent.com/assets/5414721/11822810/17b71e02-a336-11e5-8d6e-ab84442ab994.png">

**Comment by dbkaplun** [comment]
This no longer happens, closing. (Problem was regexes like `/.*/` which would match 0-length strings, creating infinite matches.)
