### ISSUE TITLE
Add support to duplicate a line, move line up or down

### ISSUE THREAD

**Issue by huangp** [slap-editor/slap#112]
duplicate a line can be achieved by select the whole line, then copy and paste but 4 steps involved: 
- select right/left infinitely 
- ctrl-c
- move down a line
- ctrl-v

In intelliJ this can be achieved with ctrl-d.

move a line up and down is also very useful.

**Comment by taneltm** [comment]
I would also like ctrl-d to duplicate the line.
Moving lines up/down would be cool, but not only 1 line - if selection spans multiple lines, all lines would move - that would be awesome.

**Comment by secrettriangle** [comment]
Closed as of d5120d6. Use `C-b`, as `deleteLeftWord` is mapped to `C-d`.
