### ISSUE TITLE
bad look with base16 color scheme 

### ISSUE THREAD

**Issue by r004** [slap-editor/slap#113]
hello;
Using slap with base16 combination; the line number plus the whole horizontal line above it is in bright yellow and not readable.
I don't know what is the color-scheme in the `README.md` of this project but is there a way to change the color of mentioned elements to match the color-scheme one uses?

**Comment by secrettriangle** [comment]
Hi @r004,

You can change your `~/.slap/config` file to override the defaults in [`slap/slap.ini`](https://github.com/slap-editor/slap/blob/master/slap.ini#L171). Does that help?

**Comment by r004** [comment]
sure; but which parts of that file is related to those elements?

**Comment by secrettriangle** [comment]
@r004, if you click that link, everything below the highlighted line should be what you're looking for. Closing this ticket.
