### ISSUE TITLE
[Linux] Slap can't interact with gpm

### ISSUE THREAD

**Issue by enedil** [slap-editor/slap#114]
When running in serial console (TTY a.k.a. Ctrl+Alt+F1,F2 and so on), I can't select files or text using [gpm](http://en.wikipedia.org/wiki/GPM_%28software%29).

**Comment by secrettriangle** [comment]
I've created an upstream issue: chjj/blessed#94 -- once that's fixed I will include the changes in slap.

**Comment by secrettriangle** [comment]
Fixed as of ac7c0eb. Please confirm!
