### ISSUE TITLE
Slap not working on my command line.

### ISSUE THREAD

**Issue by ubilli** [slap-editor/slap#116]
i love your command line software but it is not working for me.
i installed with the curl `curl -sL https://raw.githubusercontent.com/slap-editor/slap/master/install.sh | sh
` and then after installation i did `slap udemesamuel.php` this is the error i get `/usr/bin/env: node: No such file or directory
`

**Comment by taneltm** [comment]
Seems like something went wrong with the node.js install.
It would probably help if you could tell us your OS name and version.

**Comment by ubilli** [comment]
Well I am using Ubuntu 14.04, am sorry for not adding that earlier.

**Comment by secrettriangle** [comment]
@ubilli can you pastebin the command output? If there's nothing interesting, try downloading `install.sh`, then change the line on the top to `set -ex` instead of `set -e`, run it like `sh install.sh`, and pastebin that (more verbose) traceback instead.

**Comment by ubilli** [comment]
There is no large output just `/usr/bin/env: node: No such file or directory` @secrettriangle please can you explain more i did not get you.

**Comment by secrettriangle** [comment]
@ubilli does it at least print `# Installing slap...`?

    wget https://raw.githubusercontent.com/slap-editor/slap/master/install.sh
    nano install.sh

Change `set -e` to `set -ex`, then pastebin the output of `sh ./install.sh`.

**Comment by ubilli** [comment]
@Dan Kaplun This is the output, http://laravel.io/bin/PXyK8  but still not
working.

On Fri, Jan 23, 2015 at 6:15 AM, Dan Kaplun <notifications@github.com>
wrote:

> @ubilli <https://github.com/ubilli> does it at least print # Installing
> slap...?
>
> wget https://raw.githubusercontent.com/slap-editor/slap/master/install.sh
> nano install.sh
>
> Change set -e to set -ex, then pastebin the output of sh ./install.sh.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/slap-editor/slap/issues/116#issuecomment-71148877>.
>



-- 

[image: --]
Udeme . Samuel
[image: http://]about.me/udeme.samuel
<http://about.me/udeme.samuel?promo=email_sig>

*Ideas are simple but classic, Cooking ideas into products*
Computer Scientist, Programmer, Web Developer/Designer, Techpreneur,
Idealist, Jobinpal founder...
Contact: +23408123335557,+23408132229293
Email: udemesamuel256@gmail.com, udemesamuel@ymail.com...

**Comment by secrettriangle** [comment]
@ubilli looks like some PPAs or other software sources you have are unavailable, causing `apt-get update` to exit with an error code. Try removing the offending lines (looks like something related to `qbittorrent` or `hydr0g3n`) from `/etc/apt/sources.list` or `/etc/apt/sources.list.d/` and try the original installation command again:

    curl -sL https://raw.githubusercontent.com/slap-editor/slap/master/install.sh | sh

**Comment by secrettriangle** [comment]
Hey @ubilli, were you able to get it working?

**Comment by ubilli** [comment]
Hi,

I&#39;d like to add you to my professional network on LinkedIn.

- Udeme

Accept: https://www.linkedin.com/blink?simpleRedirect=30Qc3ATdzwNcjcPe3gRc3gVejkZh4BKrSBQonhFtCVF9DFgdmBSrS5CfnBBiShBsC5EsOpQsSlRpRZBt6BSrCAZqSkConhzbmlQqnpKqiRQsSlRpORIrmkZpSVFqSdxsDgCpnhFtCV9pSlipn9Mfm4Ct3kJcP1UrSNFe6AJsmgMrzlGbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054839665991680_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=7gRbjcMu6ZIqjxFbn5Ac6URqyQZp6BB9DsTt6dSpClTgCZDkztckzhkuBhphS9Ik68SiQpJh4x4pTdmunh2okpEbl1LqR1drkMTsPlAhnxbqARdq4pde7dyi5xJr4Jih4oStToSljtodCdirDwUilphs6dxsB9kr58RmnwTtCUMgAdFcmENrC9Gi4MVumtjgzgTpjxnqzphunlVj4lPkkZAhAx3m6sMi3AVhjlcqQJvunpEr3tRold3mB13qCAMoTpcbl99dARMe7Blgk51pQUNcCZQsPBGsRZ7kk4Zp6BLr2pQsSlRpRZBt6BSrCAZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCt3kJcP1UrSNFe6AJsmgMrzlGbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5994054839665991680_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoipQsSlRpRZBt6BSrCAZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4Ct3kJcP1UrSNFe6AJsmgMrzlGbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054839665991680_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by ubilli** [comment]
Hi,

I&#39;d like to add you to my professional network on LinkedIn.

- Udeme

Accept: https://www.linkedin.com/blink?simpleRedirect=0Sej8Te3oNc3sPcPwQdj0QejARfkh9rCZFt65QqnpKqipmp5FvrAFmhPRVpkJApn9xq7cCt7dBtmtvpnhFtCVFfmJB9C5QoORBt6BSrCAJt7dBtmsJr6RBfmtKqmJzon9Q9ClQqnpKimtBkClOs3Rx9CoObjARu6ZIqjxFbn5BdjwNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840379023360_500&markAsRead=


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=pz8JejlUrSNFe6AJsmkRe35TfmhFpipph4xLr4YOrRhzmz8RtD9SdSBMrT9yt4pIhBF8jRZHj7F4rjt2ildpln1vgzgSsm9Tjl9BqTFLgkJ6jD5lcP5DpSpDrCxCrjB3rB1SdmRzoRdJtkFgkntGs3dfoCl8sSh5tkthkyRkukRlcShme6xmjB1WjCNKl69odkB2lQhiunpNpk5PmBtdekBpi5xocRd7oDBfc5t6r4FctDpWcShzhmthqj9DsScOe5sRt6tcs3xVlk51gntEcT9McAVigkNUhR51fmhFrSMCt7dBtmtvpnhFtCVFfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9CoObjARu6ZIqjxFbn5BdjwNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5994054840379023360_500&amp;markAsRead= Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ct7dBtmtvpnhFtCVFfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9CoObjARu6ZIqjxFbn5BdjwNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840379023360_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by secrettriangle** [comment]
Closing this ticket, but feel free to comment if you have any more problems!

**Comment by ubilli** [comment]
Udeme Samuel would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Md30VdPoUcj4PcPwQdj0QejARfkh9rCZFt65QqnpKqipWk3lFtCZxpzRVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zcZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCpnhFtCV9pSlipn9Mfm4CsjoJs6BLqClPe6AJsmgMrzlGbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054839665991680_500&markAsRead=

View Udeme Samuel&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=3ARd3kMczANcjR4in9BoCRBripQu6lQnSlIqmpLsD0ZsTgCrT9Bq3RJ9zgZqmMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCtD1KfngCsjoJs6BLqClPe6AJsmgMrzlGbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054839665991680_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1JrSd5cylytmxQqmt5cylVr71Bsz0Q9mgNpjsUd3cMpmcVdz5xczAPpC4VemgMcj4Mc30Mc30MpCcOem8Pd34NdzgQejdyoz9xpm9xe35AdztAc38Tej8Sc69Acj8Od3BxcmoUozdBoz4Mc48O9nBIs6lOfmNFomRB9z0Sc30OfmhF9z0Qc3ATdzwNcjcPe3gRc3gVejkZp6BD9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DhUpnhvoDlPrDkJdiRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpyRIrmkZpSVFqSdxsDgCrSZDfngCsjoJs6BLqClPe6AJsmgMrzlGbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054839665991680_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=1NdyRMqmZGpncUqiRNp31KdmEJfmhFpipRtnBVlTdPsAUQdTh7u6dkpAVFgnBvumxWs6F4dCMQumlKjklEgPlWjjpFumBxp35FoS9Sjlp4t3lUc5xAmBFBunlLgDtemzxCoQdfdTpQilcOc5t9oQpLomcTj5xxokBEdQNoqkJbq4dQrShJlzBRgk52miRqhRhGu6xcsD93jRgOhQJWdPcPi65irP1Mr71bt4lWhT9ns59FkRFfgThBoPh2k5BGcmRou7t7k6gJempWlk51gntNk4BPj7AQkAtbi551fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCsjoJs6BLqClPe6AJsmgMrzlGbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5994054839665991680_500&amp;markAsRead=This email was intended for slap-editor/slap. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4CsjoJs6BLqClPe6AJsmgMrzlGbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054839665991680_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by ubilli** [comment]
Udeme Samuel would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=3oVczsUdz4MdPcPe3gRc3gVejkZh4BKrSBQonhFtCVF9BpAmBZKiBp7fnBBiShBsC5EsOpQu6lQnThMpmdzojRPt2pLsClEfmQCcPRFr2oNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpzRHpipBt6BSrABDpl9BsD0ZoipDbn4Qc6FzsPxFbn5BdjwNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840379023360_500&markAsRead=

View Udeme Samuel&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=ejkQdj0Oej4Nfkh9sClyrmlJ9DhUpnhvpmNFpCZOs3RPt2pLsClEfmQCd3RFr2oNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpzRHpipSs6UZt2pDbn4Qc6FzsPxFbn5BdjwNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840379023360_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6RLoQkO9m9Rq7hFpQkO9nBIs6lOc3gBp35BdPwQcP1BoPAScm4OejsMoCkTp30Ncj0Mc30Mc31CoP8Vej0QejoOcz8ScSoQcmkSp6cTe30Sdj4MojsMcS4Np39yom5xpzhxdjxycSlycj0Mgz8BumNMpn8Zr6BxrmkCc3oMc38Zp6ACdzAOdPwScj0TcPcUd3kMd3AVdjRAqmsCcj1vsClArCBJpn9vt7dBtmtvt7dOqmoZqSkCt7xBt5ZytndKtiQRbm9RsSVRbj4MnT9Bp6VFrmlOnThPpnlDnThPsCBCbmNJpjRDrCBHoS5Ot2pLrSsZt2pDbn4Qc6FzsPxFbn5BdjwNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840379023360_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=pORNd31GoTcUqiRNpjkUcnsZp6BB9z1Ad49Ps5F1tPsOdAZlgBpjm5FolANemCAPjkgSq4FFq7xxsPB9cl5gu5p3uDpKoDhqsyRjgAFxsQljdlkRqTBkt6wNdmwPun59l4dGkQNyd65NhnBoulBeuDxksk9BjP1fsQ5KiB1bd5dnk75Nk6QTnQpapCxvhAcMsQ9Op7pHd3pgjPhHcQdOt7lMrlwNglhopAJAqkx8jnx2s7BvcQVmsDBGmj56c3xPd7oMq3hVpTFlgk51tQVVrjcVtkZ2l4t5kk4Zp6BLr2oNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpzRHpiphdzdAhktElApOrkphgjRKpmJLl6hFripKtmMZt2pDbn4Qc6FzsPxFbn5BdjwNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5994054840379023360_500&amp;markAsRead=This email was intended for slap-editor/slap. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpzRHpipIsBlBoSBSsCljsClJrThPtmcZoipDbn4Qc6FzsPxFbn5BdjwNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840379023360_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by secrettriangle** [comment]
@ubilli could you please stop sending these? Thanks.

**Comment by ubilli** [comment]
Udeme Samuel would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=30Qc3ATdzwNcjcPe3gRc3gVejkZh4BKrSBQonhFtCVF9DFgdmBSrS5CfnBBiShBsC5EsOpQu6lQnThMpmdzojRPt2pLsClEfmQCcPRFr2oNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCpnhFtCV9pSlipn9Mfm4Cuz4JcDpQtCkOemAJsmgMrzlGbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054839665991680_500&markAsRead=

View Udeme Samuel&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=ejkQdj0Oej4Nfkh9sClyrmlJ9DhUpnhvpmNFpCZOs3RPt2pLsClEfmQCd3RFr2oNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCtD1KfngCuz4JcDpQtCkOemAJsmgMrzlGbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054839665991680_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2lAcmkTe3gPc6lzejoNoj8VcSpxejBAc34Nc30Mc30Mc6pzczBycPgNcjoQd3APoC8OomlyojwNp3oTp30OdPAOdz1yp34OczgVoj5Ce68Ppm8Nc312cylVr71BszRIqm5JpioMdz0MczRAqioMd30VdPoUcj4PcPwQdj0QejARfmhFpOoNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCt7xBt5ZytndKtiQSbm9RsSVRbj4MnT9Bp6VFrmlOnThPpnlDnShKrSdBsORIrmkZpSVFqSdxsDgCrSZDfngCuz4JcDpQtCkOemAJsmgMrzlGbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054839665991680_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=7ENbj9St7pBczBFbn5Ac6URqyQZp6BB9zgPpnx4pkAJrSNWiPhjd39ipnpikThSpj4RjAlKi5BgsAtnrBFCtP5qr2R6oPAPhTlhlmZRnStAonFlsD1elzd1lP5zgl17tSNMhD5DpQZ7ok9vq5dgk31zsTlmhRxRtS9SjRpli5BMryRfmCNRp7sPrzt5cnBnpPoOln5OtCwUd7FIjOQMcAlPsSdzgQtHuAtiqTBdjkxOdDhgkl1SlmhEtP0RtANosnBenRFjpTt3hj1lgk51klxDu6F2hjhooTt5kk4Zp6BLr2oNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCkjoPp4l7q5p6sCR6kk4ZrClHrRhAqmQCrDlIfngCuz4JcDpQtCkOemAJsmgMrzlGbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5994054839665991680_500&amp;markAsRead=This email was intended for slap-editor/slap. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=0Ue3sQfmh9pmNzqnhOoioNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncZqSkCr79lpmdFtD9BkT9BrmZQsTlzfm4Cuz4JcDpQtCkOemAJsmgMrzlGbjRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054839665991680_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by ubilli** [comment]
Udeme Samuel would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0Sej8Te3oNc3sPcPwQdj0QejARfkh9rCZFt65QqnpKqipmp5FvrAFmhPRVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zcZqmMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9ClQqnpKimtBkClOs3Rx9DASbjtBd79zczBFbn5BdjwNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840379023360_500&markAsRead=

View Udeme Samuel&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=3ARd3kMczANcjR4in9BoCRBripQu6lQnSlIqmpLsD0ZsTgCrT9Bq3RJ9zgZqmMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9DpMrzRQ9DASbjtBd79zczBFbn5BdjwNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840379023360_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6RLoQkO9m9Rq7hFpQkO9nBIs6lOc3gBp35BdPwQcP1BoPAScm4OejsMoCkTp30Ncj0Mc30Mc31CoP8Vej0QejoOcz8ScSoQcmkSp6cTe30Sdj4MojsMcS4Np39yom5xpzhxdjxycSlycj0Mgz8BumNMpn8Zr6BxrmkCc3oMc38Zp6ACdzAOdPwScj0TcPcUd3kMd3AVdjRAqmsCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9DhUpnhvoDlPrDkJdyRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncJr6RBfmtKqmJzon9Q9CZLpPRQ9DASbjtBd79zczBFbn5BdjwNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840379023360_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=ujoJdSkQsCcOemAJsmkRe35TfmhFpipddj9ocQtFpBhSsRFOdiRArD0RjBlJl3tjul5Bh3dUlj9DcTBVhzdOlztcdQNnbkwVlmN4gjtVt7lcmlYUr49xtTB4u3dnl7xvd5hIoTx6jAtWhQJPkANJpjcPtQJleltmk65niSFJs4wPsQhJqSlIljx4kmNBu75npRhqcDtqbmJjon9iiz5OpStvtT9PjAplejxCm30MkAxJq31WqCxnt6BhkkARpRh2rn58i6Foh4oMlk51gl52hnxDdktOl4dchB51fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9DASbjtBd79zczBFbn5BdjwNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5994054840379023360_500&amp;markAsRead=This email was intended for slap-editor/slap. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9DASbjtBd79zczBFbn5BdjwNtPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5994054840379023360_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by secrettriangle** [comment]
I've locked this issue. Please feel free to open a new issue.
