### ISSUE TITLE
(C-c by default), cut (C-x), and paste (C-v) bindings do not work

### ISSUE THREAD

**Issue by cubus50** [slap-editor/slap#119]
With the latest version only (C-c by default), cut (C-x), and paste (C-v) bindings do not work.
Everything ok with the old version. OS "Debian wheezy", slap-clipboard plugin and xclip is installed.
node -v  --  version: v0.10.33
npm -v   --  version: 1.4.28

thanks
robert

**Comment by secrettriangle** [comment]
Confirmed. Will be fixed soon!

**Comment by secrettriangle** [comment]
In the meantime, follow the instructions on `https://github.com/slap-editor/slap-clipboard-plugin#installation` to re-enable clipboard support.

**Comment by secrettriangle** [comment]
Fixed as of `57ed4a9`, included in `0.1.1`. Run `npm install -g slap` to update. Please confirm!

**Comment by cubus50** [comment]
The fix works for first tests correctly.

Good work, thank you.

robert imhof


Am 01.02.2015 um 15:46 schrieb Dan Kaplun:
