### ISSUE TITLE
Error after hitting F2 for help or opening a file

### ISSUE THREAD

**Issue by taneltm** [slap-editor/slap#120]
Slap version 0.1.1
![slap 2015-02-02 21 02 10](https://cloud.githubusercontent.com/assets/5690464/6006895/fa8d0842-ab1e-11e4-9121-a642d5c41e2c.png)

In addition, in the header it says "Help: f2", I think it should be "F2" ;)

**Comment by taneltm** [comment]
Ok, this issue is not related to F2 - also seems to happen when opening any file.

**Comment by secrettriangle** [comment]
Thanks for reporting... I've been very busy moving, but this will be fixed ASAP!
