### ISSUE TITLE
[bug] Won't open in Node v0.12

### ISSUE THREAD

**Issue by davidchase** [slap-editor/slap#130]
I use nvm and with `v0.10.36` everything is fine, however i recently installed `v0.12.0` 

and with that installed `slap` wont open any files.

It also worked on `v0.11.14` but not `0.11.15` or `0.11.16`

The slap.log generated the following output

```
[ [32m'TypeError: String.prototype.blink called on null or undefined'[39m,
     [32m'    at blink (native)'[39m,
     [32m'    at FindForm.Element.sattr (/usr/local/lib/node_modules/slap/node_modules/blessed/lib/widget.js:1898:44)'[39m,
     [32m'    at FindForm.Element._parseAttr (/usr/local/lib/node_modules/slap/node_modules/blessed/lib/widget.js:2120:20)'[39m,
     [32m'    at FindForm.Element.parseContent (/usr/local/lib/node_modules/slap/node_modules/blessed/lib/widget.js:2008:28)'[39m,
     [32m'    at FindForm.Element.render (/usr/local/lib/node_modules/slap/node_modules/blessed/lib/widget.js:3133:8)'[39m,
     [32m'    at /usr/local/lib/node_modules/slap/node_modules/blessed/lib/widget.js:639:8'[39m,
     [32m'    at Array.forEach (native)'[39m,
     [32m'    at Slap.Screen.render (/usr/local/lib/node_modules/slap/node_modules/blessed/lib/widget.js:636:17)'[39m,
     [32m'    at Slap.<anonymous> (/usr/local/lib/node_modules/slap/lib/ui/Slap.js:180:42)'[39m,
     [32m'    at Slap.render (/usr/local/lib/node_modules/slap/node_modules/lodash/dist/lodash.js:5452:27)'[39m ] }
```

any thoughts?

**Comment by secrettriangle** [comment]
Hmm... works fine here. I just did a fresh install of nvm, ran `nvm install 0.12 && node $(which slap)`.

What OS? What's the output of `which node && node -v && node -p "require('slap/package').version"`?

**Comment by davidchase** [comment]
```
Mac OS v10.10.2
/Users/davidchase/.nvm-fish/v0.12.0/bin/node
v0.12.0
0.1.10
```

**Comment by secrettriangle** [comment]
Hmm, have you tried doing the same thing from bash or zsh? My `which node` from zsh after running `source .nvm/nvm.sh`, then `nvm use 0.12` in a new shell:

    /Users/dan/.nvm/versions/node/v0.12.0/bin/node`

I'll be active on [IRC](http://webchat.freenode.net/?channels=slap) for a little while; stop by and we can collaboratively debug.

**Comment by davidchase** [comment]
same error when running in bash, doesnt do anything with a given file :(

**Comment by secrettriangle** [comment]
That error is very strange, especially considering `lib/ui/Slap.js:180` doesn't directly lead to `Screen.render`... Try `npm rm -g slap && npm install -g slap` and try again.

**Comment by davidchase** [comment]
I got an error during installation
```
[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!
```

**Comment by secrettriangle** [comment]
Can you paste the whole traceback (in a pastebin)?

**Comment by davidchase** [comment]
sure http://pastebin.com/0D3vQKp1

**Comment by secrettriangle** [comment]
That shouldn't be too big a problem, but copy/paste support might not work. Strange though.

Does slap run now? Can you delete your slap.log, try again, and pastebin the whole file?

**Comment by davidchase** [comment]
No it does work still, it doesnt generate a slap.log either.. i ran `slap index.js` and it blinked and did nothing

**Comment by secrettriangle** [comment]
Try running `which -a node` and `/path/to/default/node $(which slap)`.

**Comment by davidchase** [comment]
I tried to install node without nvm as well
```
/Users/davidchase/.nvm-fish/v0.12.0/bin/node
/usr/local/bin/node
```
> /path/to/default/node $(which slap)

Running that command seems to just have slap blink and do nothing

**Comment by secrettriangle** [comment]
@davidchase my guess you're having fish or nvm issues. Try a clean install of node, npm, and slap on bash or zsh, optionally using [n](https://github.com/tj/n) for version management. I don't want to spend any more time on this on Github issues, so stop by the [IRC](http://webchat.freenode.net/?channels=slap) and I'll try to help with fish/nvm if I'm around.
