### ISSUE TITLE
Factor out some widgets into blessed or blessed-contrib

### ISSUE THREAD

**Issue by dbkaplun** [slap-editor/slap#139]
The following widgets in [lib/ui](https://github.com/slap-editor/slap/tree/master/lib/ui) are not slap-specific and can be factored out:

* BaseElement (can be added as part of `blessed.Node`/`blessed.Element`)
* Button (can be added as part of `blessed.Button`)
* Editor (might replace `blessed.Textarea`)
* Field (might replace `blessed.Input`)
* FileBrowser (see also #22 and [secrettriangle/slap@issue-32](https://github.com/secrettriangle/slap/commits/issue-32))

Lots of other logic can likely be factored out as well.

**Comment by secrettriangle** [comment]
@chjj, what do you think?

**Comment by chjj** [comment]
I really like the Editor element, but it my be too texteditor-like for Blessed (all the keybinds for example). Maybe we could implement some of the editor features in textarea? I'll have to look at the other improvements.

**Comment by dbkaplun** [comment]
Closing, see [editor-widget](https://github.com/slap-editor/editor-widget) and [base-widget](https://github.com/slap-editor/base-widget).
