### ISSUE TITLE
iTerm2 + single character selection not working

### ISSUE THREAD

**Issue by Nuclearfossil** [slap-editor/slap#145]
On OSX, running on iTerm2.  Just started using slap so I'm on what's essentially the 'head' version.

S-Arrow (any arrow) doesn't select.

**Comment by secrettriangle** [comment]
@Nuclearfossil that's very strange, as that's exactly what I use for slap. Does it work in Terminal.app? Try changing `logger.level` to `debug` or `silly` in `~/.slap/config` and tailing `~/.slap/slap.log` to see how slap's picking up your keystrokes. Also see if your iTerm2 settings aren't wonky if you haven't already.

**Comment by Nuclearfossil** [comment]
Works fine in terminal and a no-go in iTerm2.

Here's the contents of the log file:

2015-04-02T17:55:24.907Z - info: starting...
2015-04-02T17:55:25.769Z - info: loaded plugin: slap-clipboard-plugin
2015-04-02T18:00:13.338Z - info: starting...
2015-04-02T18:00:13.967Z - info: loaded plugin: slap-clipboard-plugin
2015-04-02T18:04:06.272Z - info: starting...
2015-04-02T18:04:06.914Z - info: loaded plugin: slap-clipboard-plugin
2015-04-02T18:10:56.996Z - info: starting...
2015-04-02T18:10:57.879Z - info: loaded plugin: slap-clipboard-plugin
2015-04-02T22:33:21.625Z - info: starting...
2015-04-02T22:33:22.545Z - info: loaded plugin: slap-clipboard-plugin
2015-04-02T22:34:18.192Z - info: starting...
2015-04-02T22:34:19.001Z - info: loaded plugin: slap-clipboard-plugin
2015-04-02T22:35:09.148Z - info: starting...
2015-04-02T22:35:09.151Z - verbose: configuration:
{ editor:
   { pageLines: 10,
     doubleClickDuration: 600,
     defaultEncoding: 'UTF-8',
     highlight: true,
     buffer:
      { useSpaces: true,
        tabSize: 2,
        visibleWhiteSpace: false,
        visibleLineEndings: false,
        cursorPadding: { top: 2, left: 2, right: 2, bottom: 2 } },
     gutter:
      { width: 6,
        lineNumberWidth: 4,
        style: { bg: 'magenta', currentLine: '{white-bg}{magenta-fg}{bold}'
} },
     bindings:
      { goLeft: 'left',
        goLeftWord: [ 'C-left', 'M-left', '\u001b\u001b[D', 'M-b', 'M-S-b'
],
        goLeftInfinity: [ 'home', 'C-a' ],
        goRight: 'right',
        goRightWord: [ 'C-right', 'M-right', '\u001b\u001b[C', 'M-f',
'M-S-f' ],
        goRightInfinity: [ 'end', 'C-e' ],
        goUpParagraph: [ '\u001b\u001b[A', 'C-up', 'M-up', 'M-{' ],
        goUp: 'up',
        goUpPage: 'pageup',
        goUpInfinity: [ 'C-home', 'M-home', 'M-<' ],
        goDownParagraph: [ '\u001b\u001b[B', 'C-down', 'M-down', 'M-}' ],
        goDown: 'down',
        goDownPage: 'pagedown',
        goDownInfinity: [ 'C-end', 'M-end', 'M->' ],
        goMatchingBracket: [ 'C-m', 'C-]', '\u001d' ],
        selectLeft: 'S-left',
        selectLeftWord: [ 'C-S-left', 'M-S-left' ],
        selectLeftInfinity: 'S-home',
        selectRight: 'S-right',
        selectRightWord: [ 'C-S-right', 'M-S-right' ],
        selectRightInfinity: 'S-end',
        selectUp: 'S-up',
        selectUpParagraph: [ 'C-S-up', 'M-S-up' ],
        selectUpPage: 'S-pageup',
        selectUpInfinity: [ 'C-S-home', 'M-S-home' ],
        selectDown: 'S-down',
        selectDownParagraph: [ 'C-S-down', 'M-S-down' ],
        selectDownPage: 'S-pagedown',
        selectDownInfinity: [ 'C-S-end', 'M-S-end' ],
        selectMatchingBracket: 'C-S-m',
        deleteLeft: 'backspace',
        deleteRight: 'delete',
        deleteLeftWord: [ 'C-backspace', 'M-backspace', 'C-d', 'M-delete' ],
        deleteRightWord: [ 'C-delete', 'M-d' ],
        deleteLeftInfinity: [ 'C-S-backspace', 'M-S-backspace' ],
        deleteRightInfinity: [ 'C-S-delete', 'M-S-delete' ],
        deleteLine: 'C-k',
        duplicateLine: 'C-b',
        indent: [ 'tab', 'C-tab' ],
        dedent: 'S-tab',
        undo: 'C-z',
        redo: 'C-y',
        focusNext: false,
        focusPrev: false },
     style:
      { selection: '{cyan-bg}',
        match: '{yellow-bg}',
        matchingBracket: '{green-bg}{bold}',
        mismatchedBracket: '{red-bg}{bold}',
        whiteSpace: '{magenta-fg}',
        keyword: '{red-fg}',
        built_in: '{yellow-fg}',
        preprocessor: '{red-fg}',
        title: '{underline}',
        params: '{bold}',
        class: '',
        function: '',
        decorator: '{bold}',
        shebang: '{yellow-bg}{black-fg}',
        variable: '{yellow-fg}',
        operator: '{green-fg}',
        subst: '',
        number: '{green-fg}{bold}',
        string: '{green-fg}{bold}',
        regexp: '{green-fg}{bold}',
        literal: '{green-fg}{bold}',
        comment: '{white-bg}{black-fg}',
        header: '{bold}',
        strong: '{bold}',
        code: '{green-fg}',
        link_label: '',
        link_url: '{yellow-fg}',
        bullet: '{blue-fg}',
        attribute: '',
        value: '',
        setting: '',
        label: '',
        symbol: '',
        constant: '' },
     perf: { matchesRenderThrottle: 150, updateContentThrottle: 16 } },
  header:
   { messageDuration: 5000,
     blinkRate: 500,
     headerPosition: 'top',
     style:
      { bg: 'magenta',
        changed: '{yellow-fg}{bold}',
        info: '{blue-bg}{white-fg}',
        success: '{green-bg}{white-fg}',
        warning: '{yellow-bg}{black-fg}',
        error: '{red-bg}{white-fg}',
        blinkStyle: '{inverse}',
        overwrite: '{red-bg}{white-fg}' } },
  fileBrowser: { width: 12, selectedBg: 'blue' },
  logger: { dir: '/Users/amatheson/.slap', level: 'debug' },
  bindings:
   { new: 'C-n',
     open: 'C-o',
     nextPane: 'C-M-pagedown',
     prevPane: 'C-M-pageup',
     toggleFileBrowser: 'f10',
     toggleInsertMode: 'insert',
     quit: 'C-q',
     help: 'f2' },
  perf: { profile: false, renderThrottle: null },
  field:
   { buffer: { cursorPadding: { left: 2, right: 2, top: 0, bottom: 0 } },
     bindings: { submit: 'enter' },
     style: { default: '{underline}' } },
  pane: { bindings: { saveAs: 'C-s', close: 'C-w', find: 'C-f', goLine:
'C-g' } },
  form:
   { bindings: { cancel: 'escape' },
     baseFind: { bindings: { next: [ 'enter', 'down' ], prev: 'up' } },
     style: { bg: 'magenta', bold: true },
     find: { perf: { findThrottle: 150 } } },
  dialog: { bindings: { hide: 'escape' }, style: { bg: 'magenta' } },
  element:
   { bindings:
      { focusNext: [ 'tab', 'right' ],
        focusPrev: [ 'S-tab', 'left' ] } },
  button:
   { style:
      { bg: 'white',
        fg: 'black',
        bold: true,
        hover: { bg: 'blue', fg: 'white' } },
     success: { style: { hover: { bg: 'green' } } },
     warning: { style: { hover: { bg: 'yellow' } } },
     danger: { style: { hover: { bg: 'red' } } } },
  _: [ 'setup.py' ],
  configs: [ '/Users/amatheson/.slap/config' ],
  config: '/Users/amatheson/.slap/config' }
2015-04-02T22:35:09.564Z - debug: blur FileBrowser
2015-04-02T22:35:09.565Z - debug: focus Pane
2015-04-02T22:35:09.567Z - debug: blur Pane
2015-04-02T22:35:09.568Z - debug: focus Editor
2015-04-02T22:35:10.103Z - info: loaded plugin: slap-clipboard-plugin
2015-04-02T22:35:23.806Z - debug: blur Editor
2015-04-02T22:35:23.806Z - debug: focus FileBrowser

Nothing out of the ordinary there.  My bash_profile is fairly innocuous.

## for Docker
export DOCKER_CERT_PATH=$HOME/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1
export DOCKER_HOST=tcp://localhost:4243

**Comment by Nuclearfossil** [comment]
the only other thing to note: my terminal emulation is set to
xterm-256color and character encoding is Unicode (UTF-8).

**Comment by secrettriangle** [comment]
Your iTerm2 settings are most likely screwing with Shift+arrow. You can check by going to Preferences->Profiles->(your profile)->Keys, or Preferences->Keys.

To make `~/.slap/slap.log` log keystrokes, change `logger.level` to `silly` in `~/.slap/config`. See [default-config.ini](https://github.com/slap-editor/slap/blob/master/default-config.ini) and [slap.ini](https://github.com/slap-editor/slap/blob/master/slap.ini).

**Comment by Nuclearfossil** [comment]
I don't think that's the case; emacs works fine with shift+arrow, but I'll
confirm.

**Comment by secrettriangle** [comment]
No problem. Join us in [#slap](http://webchat.freenode.net/?channels=slap) and we'll continue debugging there. Closing this ticket.

**Comment by Nuclearfossil** [comment]
Shift+Left/right arrows are not changed from the default iTerm2 settings:

Shift+Left: Send ^[[C
Shift+right: Send ^[[D
