### ISSUE TITLE
setting fileBrowser to width 0 in the ini makes it 100% instead

### ISSUE THREAD

**Issue by nilsgey** [slap-editor/slap#153]
I wanted to permanently disable the file browser. 
The only option I found was to set the width of the pane in the ini to 0. However, the size becomes 100% then.

I suspect even with size 0 the filebrowser pane would be still active (e.g. by using a shortcut to toggle into it) so it might not a good idea to allow size 0 at all.

**Comment by chjj** [comment]
I have to agree with nilsgey. This is partially blessed's fault: it was never meant to accomodate 0 widths and heights. If you want an element hidden, you should call `.hide()`. I'll work on a fix to allow 0 widths though.

**Comment by secrettriangle** [comment]
@nilsgey this will be fixed with the next release of slap, which will include the (as of yet nonexistent) next release of blessed.

@chjj just tested that commit, works great, thanks!

**Comment by secrettriangle** [comment]
@nilsgey this fix has been released as part of 0.1.25. Enjoy!
