### ISSUE TITLE
F10 doesn't hide sidebar

### ISSUE THREAD

**Issue by moomoohk** [slap-editor/slap#155]

**Comment by secrettriangle** [comment]
Can you run slap with `--logger.level = debug`, try again, and pastebin your `~/.slap/slap.log` please?

**Comment by moomoohk** [comment]
http://pastebin.com/ZN1erstz

**Comment by secrettriangle** [comment]
Did I say `debug`? I meant `silly`. Sorry about that!

**Comment by moomoohk** [comment]
http://pastebin.com/raw.php?i=ETA96GKa

**Comment by secrettriangle** [comment]
Hmm, looks like the `f10` keystroke is not even reaching slap, as slap will log all keystrokes, even unknown ones. Check to see if your OS or some other application is trapping `f10`.

PS: the next release of slap will allow you to completely disable the filebrowser by setting `fileBrowser.width = 0` (see #153).

**Comment by secrettriangle** [comment]
Forgot to mention, of course you can change the keybinding to something other than `f10`.

**Comment by moomoohk** [comment]
Looks like that's what it was (Mission Control -> Application Windows). Disabling that solves the issue.

**Comment by secrettriangle** [comment]
Ah, in that case you should be able to leave that on and just hold `fn` before pressing `f10`! :)
