### ISSUE TITLE
Sometimes slap has one keystroke's worth of input lag on OSX iojs and node 0.12 (but not 0.10)

### ISSUE THREAD

**Issue by dbkaplun** [slap-editor/slap#156]
Maybe 10% of the time, when you're typing, the last keystroke isn't shown on the screen. After some debugging, I've found that the keypress is being registered, but stdout is simply not flushed. As it turns out, the whole event loop shuts down, i.e. `setInterval` callbacks stop getting called. However, as soon as I send any more data to stdin, the event loop works again and `setInterval` callbacks are called again, so it seems like a blocking read is the issue somewhere.

**Comment by steelbrain** [comment]
Bump

**Comment by secrettriangle** [comment]
See also joyent/node#9310 and libuv/libuv#304.

**Comment by dbkaplun** [comment]
A fix has been merged into libuv. Soon!

**Comment by dbkaplun** [comment]
Looks like this issue was fixed with Node 0.12.5. Please confirm!

**Comment by steelbrain** [comment]
@dbkaplun I am not in a position to confirm this slap bug for the next few months :smiley:
Sorry.

**Comment by dbkaplun** [comment]
Closing. If issues continue, I will consider reopening.
