### ISSUE TITLE
Install slap locally

### ISSUE THREAD

**Issue by puneetsl** [slap-editor/slap#163]
If I do not have root permissions to install Node, slap should be able to install and run locally. 

This can be a great enhancement

**Comment by puneetsl** [comment]
I fond a way to install `npm` locally and that in turn would install slap locally. Would blog about it

**Comment by dbkaplun** [comment]
As a matter of fact, even with `npm` installed globally, you can install slap locally:
```sh
$ npm install slap # installs into ./node_modules/slap
```

You can then run `cd node_modules/slap && ./index.js <file1> <file2>`. You can add `$CWD/node_modules/.bin` to your `PATH` if you want `slap` accessible anywhere.

Glad you got it working!
