### ISSUE TITLE
Change config file to be in ~/.config/slap/

### ISSUE THREAD

**Issue by emoryy** [slap-editor/slap#176]

**Comment by derhuerst** [comment]
:+1: 

There are many reasons why I think this is good. When my dotfiles are in `~/.config` instead of `~`,

- I can easily put them under version control.
- I can them quickly if I need to set up my machine.
- I can easily try out others' dotfiles.
- There is less noise in `~`.

**Comment by dbkaplun** [comment]
slap uses [rc](https://github.com/dominictarr/rc) for configuration, so actually you can move your `~/.slap` into `~/.config/slap` without any consequences. See [here](https://github.com/dominictarr/rc#standards) for all acceptable config locations.

**Comment by emoryy** [comment]
Thanks! Moving the config file seems to be working and Ok.
However slap still creates a .slap directory for its log file.

**Comment by dbkaplun** [comment]
You should be able to use something like:
```ini
[logger]
file = "~/.config/slap/slap.log"
```

Or the equivalent CLI option to change the log file path. I'm not at a computer right now so I can't test it, but let me know if it works!

**Comment by dbkaplun** [comment]
Closing. Please comment if you have issues and I'll reopen!
