### ISSUE TITLE
Chinese Charaters are not displayed correctly in slap

### ISSUE THREAD

**Issue by iskl** [slap-editor/slap#182]
Chinese Characters are all displayed as ???? in slap, both in file browser and text editor

**Comment by dbkaplun** [comment]
Hey @iski, thanks for reporting! Can you try `slap --screenOpts.fullUnicode true`? If that works, you can save it into `~/.slap/config`.

**Comment by Iski** [comment]
Hey,

I didn't report anything, I'm not using GitHub.

Kind Regards

2015-08-05 15:33 GMT+02:00 Dan Kaplun <notifications@github.com>:

**Comment by dbkaplun** [comment]
Oops, that was for @iskl, sorry about that!

**Comment by chjj** [comment]
@dbkaplun, did you have trouble when navigating text with double-width characters? I had to alter Textarea a bit myself. I'm sorry it's so annoying. Unicode is annoying though, especially utf-16.

**Comment by iskl** [comment]
Hi, @dbkaplun , Thanks for your help. Sorry to reply so late. After adding the argument, Chinese Characters could be shown correctly. Thanks.
