### ISSUE TITLE
complete key bindings not found in readme, slap.ini, or F2

### ISSUE THREAD

**Issue by codyzu** [slap-editor/slap#184]
The readme says:

> Unfortunately most terminal emulators do not support certain keystrokes and as such there is no way to handle them. These include C-backspace, S-home/end, and S-pageup/down. Most of these actions have alternate keybindings, inspired by emacs and other editors, but if you find one that doesn't work...

It is not clear where a complete listing of keybindings can be found. The default slap.ini only has the *very* basic keybindings (quit, saveas, etc...).

I think the readme (or maybe slap in general) needs a complete listing of keybindings. This would be useful for both learning slap and knowing what can be customized in the ini.

I will improve the documentation if I know where to find the info...

**Comment by dbkaplun** [comment]
Hi @codyzu,

See [default-config.ini](https://github.com/slap-editor/slap/blob/master/default-config.ini#L1-L5) which gets copied into `~/.slap/config` (if the file isn't already present). I think you are right in that the documentation for this needs to be fleshed out. How would you change the documentation to better reflect the capabilities of slap? I'd be glad to review a PR if you are inclined to write one.

**Comment by dbkaplun** [comment]
@codyzu I've updated the README with some keybindings (but not all). Let me know what keybindings you think are missing and I'll add them.
