### ISSUE TITLE
remove tree on the left

### ISSUE THREAD

**Issue by loctauxphilippe** [slap-editor/slap#214]
is there an option to remove the tree on the left, to get only the current file?
if there's one already, could someone tell me how to enable it?
thanks, slap is a great editor :smile:

**Comment by dbkaplun** [comment]
<kbd>F10</kbd>, or set the following in `~/.slap/config`:
```ini
[fileBrowser]
width = 0
```

**Comment by loctauxphilippe** [comment]
@dbkaplun thanks!
