### ISSUE TITLE
"sudo npm install -g slap@latest" requires node-nan

### ISSUE THREAD

**Issue by openbrian** [slap-editor/slap#220]
When running npm install, i got numerous compile errors.  First 

Cannot find module 'nan'

So i npm installed that.  Then i got 

../../nan/nan.h:200:47: fatal error: nan_new.h: No such file or directory

So i apt-get installed node-nan.

Finally the compile was clean.

**Comment by dbkaplun** [comment]
Thanks for the report. Closing.

**Comment by mj41** [comment]
For Fedora 23: ```dnf install nodejs-nan```
