### ISSUE TITLE
Slap flashes on screen for a split second and closes

### ISSUE THREAD

**Issue by kenmorechalfant** [slap-editor/slap#229]
No errors. It just closes immediately.

I'm on Ubuntu 14.04 using standard terminal.

**Comment by dbkaplun** [comment]
@kenmorechalfant there should be more information in `~/.slap/slap.log`. Can you paste it please?

**Comment by kenmorechalfant** [comment]
2015-11-18T21:08:16.178Z - ^[[32minfo^[[39m: loading...
    2015-11-18T21:08:35.228Z - ^[[32minfo^[[39m: loading...
    2015-11-18T21:12:16.019Z - ^[[32minfo^[[39m: loading...
    2015-11-18T21:12:33.739Z - ^[[32minfo^[[39m: loading...
    2015-11-18T21:14:49.139Z - ^[[32minfo^[[39m: loading...
    2015-11-18T21:14:55.528Z - ^[[32minfo^[[39m: loading...
    2015-11-18T21:19:20.180Z - ^[[32minfo^[[39m: loading...
    2015-11-18T21:19:42.142Z - ^[[32minfo^[[39m: loading...
    2015-11-20T00:59:40.633Z - ^[[32minfo^[[39m: loading...

**Comment by kenmorechalfant** [comment]
I also found out that if I create a new file by doing like:

    slap nonexistantfile.txt

It works and I can edit the file and save it... But once I quit and try to edit the file again with the same command the program opens for a split second and closes itself.

**Comment by dbkaplun** [comment]
Try running the same command with `--logger.level silly` at the end:
```
slap nonexistantfile.txt --logger.level silly
```

If you don't find anything in the logs, try adding `util.logger.info('L61', err)` at [lib/ui/Slap.js line 61](https://github.com/slap-editor/slap/blob/master/lib/ui/Slap.js#L61). (You can probably find it in `/usr/lib/node_modules/slap/lib/ui/Slap.js` depending on your installation.)

There is another (likely related) problem where errors during the loading process are thrown outside the current call stack, so there's no meaningful way to handle them: atom/text-buffer#110

**Comment by kenmorechalfant** [comment]
Here's the output with `--logger.level silly`

https://gist.github.com/kenmorechalfant/a827dd95b95aaf314b01

**Comment by kenmorechalfant** [comment]
So I updated Node and NPM which actually turned out to be a huge headache. I thought it would take 2 minutes but it took 2 hours. Problem after problem. But now I'm on Node 5.x and Slap seems to be working so far.
