### ISSUE TITLE
Regex Find does not work entirely

### ISSUE THREAD

**Issue by NiXXeD** [slap-editor/slap#242]
Example using `/(day \d+)/` - only highlighting one entry.
<img width="1440" alt="screen shot 2015-12-15 at 12 23 34 pm" src="https://cloud.githubusercontent.com/assets/5414721/11819688/c9673796-a326-11e5-9208-167d07234b13.png">

Attempted adding `gm` modifiers instead `/(day \d+)/gm` - No matches
<img width="1440" alt="screen shot 2015-12-15 at 12 23 46 pm" src="https://cloud.githubusercontent.com/assets/5414721/11819744/1fbfee94-a327-11e5-8ebc-2a212038f9de.png">

**Comment by NiXXeD** [comment]
Version I'm using:
slap@0.1.57

**Comment by NiXXeD** [comment]
Some quick thoughts on what the solution might be. Granted, I don't know this codebase yet, but I'm looking around =)

At this line of code: https://github.com/slap-editor/slap/blob/master/lib/ui/FindForm.js#L55
You're using a regular expression with 2 groups to match to pull the regex/modifiers.

At this line of code: https://github.com/slap-editor/slap-util/blob/master/lib/text.js#L1
You have the regex `/^\/(.+)\/([im]?)$/` which is used in the block above. The ? in this regex assumes 0 or 1 modifier, and the "g" modifier isn't included. This could be changed to `^\/.*\/[gmi]*$` based on my checks using [regex101](https://regex101.com/#javascript). This would allow any/all of the available modifiers to be present.

I haven't gotten the entire codebase set up to run locally yet, so I can't verify this entirely resolves the issue. I will submit a PR for this though.

**Comment by dbkaplun** [comment]
Hi @NiXXeD, can you please link to the document you used to test this? It seems like the issue is that non-selected matches aren't highlighted in yellow but I want to make sure. When you press <kbd>↓</kbd>or <kbd>Enter</kbd>/<kbd>↑</kbd>, does it go to the next/previous match?

**Comment by dbkaplun** [comment]
OK, I can confirm the issue. I'll take a look at this when I get a chance.

**Comment by dbkaplun** [comment]
Fixed as of v0.1.58. Thanks @NiXXeD!
