### ISSUE TITLE
Re-opening a modified file overwrites changes without confirmation

### ISSUE THREAD

**Issue by NiXXeD** [slap-editor/slap#243]
Starting with a file open, with changes:
<img width="495" alt="screen shot 2015-12-15 at 2 27 40 pm" src="https://cloud.githubusercontent.com/assets/5414721/11823161/27b35cc4-a338-11e5-9a75-1965314d4605.png">

Say you open another file:
<img width="805" alt="screen shot 2015-12-15 at 2 29 00 pm" src="https://cloud.githubusercontent.com/assets/5414721/11823164/32f61a4a-a338-11e5-9297-728aeb121836.png">

If you press your "close tab" hotkey, it goes back to the modified file as expected. But if you double click the file you had changes on from the file explorer, changes are lost without confirmation:
<img width="436" alt="screen shot 2015-12-15 at 2 29 57 pm" src="https://cloud.githubusercontent.com/assets/5414721/11823189/58c19f24-a338-11e5-8e04-8781f5fc6328.png">

**Comment by dbkaplun** [comment]
Fixed as of v0.1.58.
