### ISSUE TITLE
Multiple file support. (tabs?)

### ISSUE THREAD

**Issue by Splizard** [slap-editor/slap#249]
Can we edit multiple files at a time and have some sort of tab system to navigate?

**Comment by dbkaplun** [comment]
Next/previous tab: <kbd>Ctrl+Alt+PageUp/Down</kbd>
Close tab: <kbd>Ctrl+W</kbd>

Is that what you were looking for?

**Comment by tolgraven** [comment]
Would definitely help heaps if the open tabs were shown in the top bar, there's ample room for that too. 
Default keybindings for switching tabs aren't working for me btw (in iTerm on OS X so e.g. Fn+Ctrl+Opt+arrow).

_Awesome_ editor btw, been looking for something like this for the longest time. Big up :)

**Comment by Splizard** [comment]
Yea a visual indicator would be nice, I was unsure there was multiple file support as clicking on files in the address bar replaced the open file

**Comment by dbkaplun** [comment]
I've released a new version v0.1.59&mdash;now you can press <kbd>Ctrl+L</kbd> to show the current list of open panes. You can also cycle through the list to select a pane. Let me know what you think! Closing this issue.
