### ISSUE TITLE
Change highlight.js theme 

### ISSUE THREAD

**Issue by estebanz01** [slap-editor/slap#308]
Good day.

Is it possible to change the highlight.js theme? I want to use the `Railscast` theme that is a CSS file.

**Comment by dbkaplun** [comment]
See here: https://github.com/slap-editor/editor-widget/blob/1ceaf95cd044bdf90e28fc3aee0f7aa67a2b6b10/editor-widget.ini#L130-L180

To use this, change any of the values in your `~/.slap/config`.
