### ISSUE TITLE
Error: Module version mismatch. Expected 48, got 47.

### ISSUE THREAD

**Issue by Paarthri** [slap-editor/slap#323]
I installed slap using the command:
`curl -sL https://raw.githubusercontent.com/slap-editor/slap/master/install.sh | sh`
and when I run the command `slap`, this is what happened: http://pastebin.com/NQTj73Vx

It seems as if there is something wrong with my installation of nodejs. I don't know much about nodejs or javascript, I just wanted to use the slap-editor. What should I do to fix this problem?

**Comment by dbkaplun** [comment]
Hi @paarthri,

This usually happens when you upgrade Node after installing slap. Try to reinstall slap for your current Node version:
```sh
$ npm i -g slap
```

**Comment by Paarthri** [comment]
I did that and it still does not work. Same output.

**Comment by Paarthri** [comment]
A simple update to node fixed the problem. Thanks

**Comment by dbkaplun** [comment]
Glad to hear it @Paarthri. Thanks for the update!
