### ISSUE TITLE
Is there a way to change the syntax highlighting style?

### ISSUE THREAD

**Issue by Paarthri** [slap-editor/slap#330]
I know this uses Highlight.js.
How can I choose a style from https://github.com/isagalaev/highlight.js/tree/master/src/styles?

**Comment by dbkaplun** [comment]
You can override styles via `~/.slap/config`. See here for a list of syntax values you can change: https://github.com/slap-editor/editor-widget/blob/master/editor-widget.ini#L130

**Comment by Paarthri** [comment]
Thanks it worked!
