### ISSUE TITLE
Is Development Dead? 

### ISSUE THREAD

**Issue by edglazer** [slap-editor/slap#413]
I had a working binary for slap on MacOS at some point in the past and just reinstalled a new machine. I don't see binaries anywhere online or through homebrew, and it appears that development actively ceased in 2016?

Anybody know a different story, or where to get working binaries (because it sounds like it's not building for people?)
Thanks!

**Comment by justadropofwater** [comment]
I would also like to know the state of dev. Interested to pick this up if abandoned.

**Comment by LennyPenny** [comment]
just fork it :D

**Comment by ghost** [comment]
i think the dude has actually died to be honest, I found some obituary dated around the same time as what appears to be no more updates on social media/github etc.

https://github.com/dbkaplun
shows activity ceases in july 2018

Daniel Kaplun was born on October 19, 1990 and passed away on July 30, 2018

**Comment by justadropofwater** [comment]
> i think the dude has actually died to be honest, I found some obituary dated around the same time as what appears to be no more updates on social media/github etc.
> 
> https://github.com/dbkaplun
> shows activity ceases in july 2018
> 
> Daniel Kaplun was born on October 19, 1990 and passed away on July 30, 2018

Wow...little lost for words. :(

**Comment by edglazer** [comment]
Oh wow, this is sad. I'll close the ticket, since @electronoob provided information to answer my initial query.

**Comment by ajstrand** [comment]
If anyone is still interesting in this editor, I have a fork that runs under node 16(haven't tried 17). 

My plan is maintain the project as open source/update the codebase as i get time. 

Personally I like js more than lua/vimscript/emacs, so this editor seemed like nice change of pace. 

It also uses less resources than VSCode
