### ISSUE TITLE
Harsh default color scheme

### ISSUE THREAD

**Issue by imsky** [slap-editor/slap#72]
The color scheme could be more neutral: the sidebar items are barely readable and the magenta color for the gutter is harsh.

OS: Xubuntu 14.04

![slap](https://cloud.githubusercontent.com/assets/330895/4159487/bf93258e-34a2-11e4-9567-062c82cfd673.png)

**Comment by secrettriangle** [comment]
I've filed chjj/blessed#108 -- this will provide much more leeway with color schemes.

**Comment by dbkaplun** [comment]
slap 0.1.50 has more neutral defaults:

![screenshot](https://raw.githubusercontent.com/slap-editor/slap/master/screenshot.png)

**Comment by imsky** [comment]
great to see :+1:
