### ISSUE TITLE
Use blue as default color

### ISSUE THREAD

**Issue by dbkaplun** [slap-editor/slap#8]

**Comment by dbkaplun** [comment]
@m1so hey, saw you in #slap on Freenode looking to make slap blue. I've actually been intending to do this for quite a while but I've been focusing on other higher-priority things. If you figured this out, I'd be glad to accept a pull request! Otherwise I'm glad to help you out back in #slap.

**Comment by m1so** [comment]
Sure, I just edited few options in `~/.slap/config`. Here is the preview:

![](https://s3.amazonaws.com/f.cl.ly/items/2q3U3c422l070k3d3T0w/Slap%20blue%20bash.png)
![](https://s3.amazonaws.com/f.cl.ly/items/0S3D3h140H0q3J3o2X1p/Slap%20blue%20preview.png)

Tell me if you like it and I can send a pull request.

**Comment by dbkaplun** [comment]
Looks great! Looking forward to trying it out myself.

**Comment by dbkaplun** [comment]
Merged. Great work @m1so!
